apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-config
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  POSTGRES_HOST: {{ .Release.Name }}-postgresql
  POSTGRES_PORT: "5432"
  POSTGRES_USER: {{ .Values.postgresql.user | quote }}
  POSTGRES_DB: {{ .Values.postgresql.database | quote }}
  AUTH_ENABLED: {{ .Values.backend.env.AUTH_ENABLED | quote }}
  SCHEDULER_ENABLED: {{ .Values.backend.env.SCHEDULER_ENABLED | quote }}
  DBT_ARTIFACTS_PATH: {{ .Values.backend.env.DBT_ARTIFACTS_PATH | quote }}
  DBT_PROJECT_PATH: {{ .Values.backend.env.DBT_PROJECT_PATH | quote }}
  DBT_PROFILES_PATH: {{ .Values.backend.env.DBT_PROFILES_PATH | quote }}
  GIT_REPOS_BASE_PATH: {{ .Values.backend.env.GIT_REPOS_BASE_PATH | quote }}
